services:
  node_server:
    build:
      context: .
      dockerfile: Dockerfile
      target: node
    ports:
      - "9808:9808"
    volumes:
      - ./modules:/modules
      - ./configs:/configs
      - ./storage:/storage
      - ./server:/server

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    env_file:
      - .env
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    ports:
      - "${WEB_CONTAINER_PORT:-9998}:${WEB_CONTAINER_PORT:-9998}"
    restart: always
    volumes:
      - ./modules:/modules
      - ./configs:/configs
      - ./client:/client
      - ./storage:/storage
    depends_on:
      - node_server
volumes:
  modules: {}
  configs: {}
  storage: {}
