services:
  node_server:
    build:
      context: .
      dockerfile: Dockerfile
      target: node
    ports:
      - "9808:9808"
    volumes:
      - ./configs:/app/configs
      - ./storage:/app/storage
      - ./modules:/app/modules

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
    env_file:
      - .env
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    ports:
      - "${WEB_CONTAINER_PORT:-9998}:${WEB_CONTAINER_PORT:-9998}"
      - "${NODE_SERVER_PORT:-8887}:${NODE_SERVER_PORT:-8887}"
    restart: always
    volumes:
      - ./modules:/app/modules
      - ./configs:/app/configs
      - ./manager:/app/manager
      - ./storage:/app/storage
      - ./host:/app/host
    depends_on:
      - node_server
volumes:
  modules: {}
  configs: {}
  storage: {}
